# 사이트 설정
title: 가볍게 배워 가볍게 쓰기기
description: 로봇, AI, 생각 등등등
baseurl: "" # 사이트의 서브패스 (예: /blog)
url: "https://fridec13.github.io" # 도메인 이름
author: 김성훈
email: maybecold@naver.com
published: true
future: true
# 브라우저 캐시 무효화를 위한 빌드 버전
build_version: "1.0.0"

# SEO 관련 추가 설정
lang: ko_KR
logo: /assets/images/profile.jpg
social:
  name: 김성훈
  links:
    - https://github.com/fridec13
    - https://twitter.com/USERNAME

# 빌드 설정
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/page/:num/"

# 마크다운 확장 설정
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-paginate

# 컬렉션 설정
collections:
  wiki:
    output: true
    permalink: /:collection/:path/

# 기본 레이아웃 설정
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      image: /assets/images/default-post-image.jpg
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "post"
      comments: true
      image: /assets/images/default-wiki-image.jpg
  - scope:
      path: ""
      type: "pages"
    values:
      image: /assets/images/default-page-image.jpg

# 태그 설정
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# 카테고리 아카이브 설정
jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    category: /category/:name/

# Giscus 설정
giscus:
  repo: "fridec13/fridec13.github.io"
  repo-id: "R_kgDOOa_5_g"
  category: "General"
  category-id: "DIC_kwDOOa_5_s4CpVln"
  mapping: "pathname"
  reactions-enabled: "1"
  emit-metadata: "0"
  input-position: "bottom"
  theme: "preferred_color_scheme"
  lang: "ko"

# Sass/SCSS 설정
sass:
  sass_dir: _sass
  style: compressed

# 포함할 파일과 디렉토리
include:
  - assets/js/script.js
  - assets/css
  - assets/js
  - robots.txt
  - .htaccess

# 제외 파일 및 디렉토리
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .sass-cache
  - .jekyll-cache
  - .idea
  - .github
  - README.md
  - LICENSE
  - tmp 